# Generated by Django 6.1.1 on 2026-09-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoterequest',
            name='budget',
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
