# Generated by Django 6.1.1 on 2026-09-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='cta_button_link',
            field=models.CharField(default='#quote', max_length=300),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='cta_button_text',
            field=models.CharField(default='Start a Project', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='cta_description',
            field=models.TextField(default='Tell us about your project and discover how we can turn your idea into a powerful digital experience.'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='cta_title',
            field=models.CharField(default='Have an idea? Let’s build it together.', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='eyebrow',
            field=models.CharField(default='ABOUT OUR COMPANY', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='happy_clients',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='projects_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='value_1_description',
            field=models.TextField(default='We continuously explore better ideas, technologies and ways of solving problems.'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='value_1_title',
            field=models.CharField(default='Innovation', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='value_2_description',
            field=models.TextField(default='We focus on creating reliable, polished and maintainable digital products.'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='value_2_title',
            field=models.CharField(default='Quality', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='value_3_description',
            field=models.TextField(default='We believe strong relationships are built through transparency, communication and consistency.'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='value_3_title',
            field=models.CharField(default='Trust', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='why_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='why_point_1',
            field=models.CharField(default='Business-focused solutions', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='why_point_2',
            field=models.CharField(default='Modern and scalable technology', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='why_point_3',
            field=models.CharField(default='Clean and user-friendly experiences', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='why_point_4',
            field=models.CharField(default='Reliable long-term support', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='why_title',
            field=models.CharField(default='Why Businesses Choose Us', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='years_experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(default='We Build Digital Experiences That Move Businesses Forward', max_length=200),
        ),
    ]
