# Generated by Django 6.1.1 on 2026-09-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='Welcome to My Company', max_length=200)),
                ('title', models.CharField(default='We build modern digital solutions.', max_length=300)),
                ('description', models.TextField(blank=True)),
                ('button_text', models.CharField(default='Get Started', max_length=100)),
                ('button_link', models.CharField(default='#quote', max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
