# Generated by Django 6.1.1 on 2026-09-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homehero',
            name='title_2',
            field=models.CharField(blank=True, default='We create powerful digital experiences.', max_length=300),
        ),
        migrations.AddField(
            model_name='homehero',
            name='title_3',
            field=models.CharField(blank=True, default='We turn ideas into innovative solutions.', max_length=300),
        ),
    ]
